# processing parameters
jet_levels: ['ch']
jetR: [0.4]

debug_level: 0

do_matching: True
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
reject_tracks_fraction: 0.0
eta_max: 0.9

do_tagging: False
do_reshuffle: False
do_theory_check: False
do_sanity_check: True
do_ktbins: True

beyond_jetR: False
part_levels: ['p', 'h', 'ch']

